<script setup lang="ts">
import AppDashboard from "./AppDashboard.vue";
import AppGit from "./AppGit.vue";
import AppInbox from "./AppInbox.vue";
import AppTasks from "./AppTasks.vue";
import NoteTreeNodeItem from "./NoteTreeNodeItem.vue";
import SourceCard from "../SourceCard.vue";
import { useAppShell } from "./useAppShellRuntime";

const {
  links,
  notes,
  tasks,
  feeds,
  feedItems,
  emails,
  reviewQueue,
  gitStatus,
  jobs,
  activeView,
  search,
  error,
  loading,
  theme,
  gitBusy,
  tiktokNoteBusy,
  sourcePreviewBusy,
  gitResult,
  forcePushConfirmed,
  selectedInboxItem,
  inboxFilter,
  inboxSort,
  selectedSourceTool,
  selectedSourceLinkId,
  editingSourceLinkId,
  selectedNoteId,
  showNewNoteForm,
  editingNoteId,
  noteMetadataBusy,
  persistNoteTreeState,
  noteGroupOpenStates,
  noteTreeCollapsed,
  noteSidebarCollapsed,
  noteFiltersOpen,
  noteTreeFilters,
  noteTreeOptions,
  noteBodyTextarea,
  sourceForm,
  sourceEditForm,
  noteForm,
  noteEditForm,
  taskForm,
  feedForm,
  opmlForm,
  emailForm,
  gitForm,
  tiktokNoteForm,
  sourceTools,
  navItems,
  noteStatuses,
  currentView,
  query,
  isDarkTheme,
  sources,
  inboxSources,
  keptSources,
  openTasks,
  newFeedItems,
  newEmails,
  inboxNotes,
  inboxCount,
  inboxItems,
  visibleInboxItems,
  selectedEmail,
  selectedFeedItem,
  filteredSources,
  selectedSourceLink,
  selectedNote,
  selectedNoteHtml,
  selectedNoteParentPaths,
  noteFacets,
  notesTree,
  filteredNotes,
  noteTreeFolderPaths,
  noteTreeAllCollapsed,
  activeNoteFilterChips,
  NOTE_GROUP_STATE_STORAGE_KEY,
  NOTE_GROUP_PERSIST_KEY,
  NOTE_TREE_OPTIONS_STORAGE_KEY,
  THEME_STORAGE_KEY,
  filteredTasks,
  stats,
  noteMarkdownEditor,
  mermaidReady,
  setTheme,
  loadTheme,
  toggleTheme,
  parentPaths,
  isGroupOpen,
  openNote,
  onGroupToggle,
  loadNoteTreeState,
  persistNoteTreeStateSettings,
  loadNoteTreeOptions,
  persistNoteTreeOptions,
  visibleNotes,
  folderPaths,
  toggleWholeNoteTree,
  toggleFilterValue,
  removeNoteFilter,
  resetNoteFilters,
  renderMermaidDiagrams,
  onPersistNoteTreeChange,
  loadLinks,
  loadNotes,
  loadTasks,
  loadFeeds,
  loadFeedItems,
  loadEmails,
  loadGitStatus,
  apiError,
  addSource,
  addNote,
  openNewNoteForm,
  closeNewNoteForm,
  startEditNote,
  cancelEditNote,
  updateNote,
  deleteNote,
  suggestNoteMetadata,
  fixNoteMarkdown,
  normalizeNoteHeaders,
  noteFormMeta,
  noteKindOptions,
  applyPastedFrontmatter,
  applyNoteMetadata,
  resetNoteMetadata,
  initNoteMarkdownEditor,
  destroyNoteMarkdownEditor,
  addTask,
  addFeed,
  importOpml,
  refreshAllFeeds,
  fetchFeed,
  setFeedEnabled,
  deleteFeed,
  saveFeedItem,
  noteFeedItem,
  taskFeedItem,
  ignoreFeedItem,
  actOnFeedItem,
  importEmail,
  saveEmail,
  noteEmail,
  taskEmail,
  ignoreEmail,
  actOnEmail,
  noteSource,
  setSourceStatus,
  setReviewStatus,
  startEditSource,
  cancelEditSource,
  updateSource,
  suggestSourceTags,
  toggleTask,
  syncSecondBrain,
  createTikTokNote,
  commitSecondBrain,
  pullSecondBrain,
  pushSecondBrain,
  runGitAction,
  formatGitActionResult,
  formatSyncSummary,
  isSecondBrainSyncSummary,
  sourceStatus,
  sourceDomain,
  normalizeTags,
  gitTarget,
  hasSourceHint,
  selectEmail,
  selectFeedItem,
  closeInboxDetail,
  openInboxNote
} = useAppShell();

async function importArticle() {
  error.value = "";
  const url = sourceForm.url.trim();
  if (!url) return;

  const previewResponse = await fetch("/api/links/preview", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ url })
  });
  const preview = previewResponse.ok ? await previewResponse.json() : null;
  const payload = {
    title: preview?.title || url,
    url: preview?.url || url,
    description: preview?.description || "",
    categoryId: null,
    tags: ["status:inbox", "article", ...(preview?.tags ?? [])]
  };

  const response = await fetch("/api/links", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload)
  });
  if (!response.ok) {
    error.value = "Artikel braucht eine gueltige URL.";
    return;
  }
  (links.value as unknown[]).unshift(await response.json());
  sourceForm.url = "";
  activeView.value = "inbox";
}
</script>

<template src="./AppShell.template.html"></template>
